<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/13
 * Time: 15:28
 */

namespace myclass;


class Citys
{
    private $city1 = '[{ "name": "beijing", "cities": ["xicheng", "dongcheng", "chongwen", "xuanwu", "chaoyang", "haidian", "fengtai", "shijingshan", "mentougou", "fangshan", "tongzhou", "shunyi", "daxing", "changping", "pinggu", "huairou", "miyun", "yanqing"] },
    { "name": "tianjin", "cities": ["qingyang", "hedong", "hexi", "nankai", "hebei", "hongqiao", "tanggu", "hangu", "dagang", "dongli", "xiqing", "beichen", "jinnan", "wuqing", "baodi", "jinghai", "ninghe", "jixian", "kaifaqu"] },
    { "name": "hebei", "cities": ["shijiazhuang", "qinhuangdao", "langfang", "baoding", "handan", "tangshan", "xingtai", "hengshui", "zhangjiakou", "chengde", "cangzhou", "hengshui"] },
    { "name": "shanxi", "cities": ["taiyuan", "datong", "changzhi", "jinzhong", "yangquan", "shuozhou", "yuncheng", "linfen"] },
    { "name": "namenggu", "cities": ["huhehaote", "chifeng", "tongliao", "xilinguole", "xingan"] },
    { "name": "liaoning", "cities": ["dalian", "shenyang", "anshan", "fushun", "yingkou", "jinzhou", "dandong", "chaoyang", "liaoyang", "fuxin", "tieling", "panjin", "benxi", "huludao"] },
    { "name": "jilin", "cities": ["changchun", "jilin", "siping", "liaoyuan", "tonghua", "yanji", "baicheng", "liaoyuan", "songyuan", "linjiang", "huichun"] },
    { "name": "heilongjiang", "cities": ["haerbin", "qiqihaer", "daqing", "mudanjiang", "hegang", "jiamusi", "suihua"] },
    { "name": "shanghai", "cities": ["pudong", "yangpu", "xuhui", "jingan", "luwan", "huangpu", "putuo", "zhabei", "hongkou", "changning", "baoshan", "minxing", "jiading", "jinshan", "songjiang", "qingpu", "chongming", "fengxian", "nanhui"] },
    { "name": "jiangsu", "cities": ["nanjing", "suzhou", "wuxi", "changzhou", "yangzhou", "xuzhou", "nantong", "zhenjiang", "taizhou", "huaian", "lianyungang", "suqian", "yancheng", "huaiyin", "muyang", "zhangjiagang"] },
    { "name": "zhejiang", "cities": ["hangzhou", "jinhua", "ningbo", "wenzhou", "jiaxing", "shaoxing", "lishui", "huzhou", "taizhou", "zhoushan", "quzhou"] },
    { "name": "anhui", "cities": ["hefei", "maanshan", "bangbu", "huangshan", "wuhu", "huainan", "tongling", "fuyang", "xuancheng", "anqing"] },
    { "name": "fujian", "cities": ["fuzhou", "xiamen", "quanzhou", "zhangzhou", "nanping", "longyan", "putian", "sanming", "ningde"] },
    { "name": "jiangxi", "cities": ["nanchang", "jingdezhen", "shangrao", "pingxiang", "jiujiang", "jian", "yichun", "yingtan", "xinyu", "ganzhou"] },
    { "name": "shandong", "cities": ["qingdao", "jinan", "zibo", "yantai", "taian", "linyi", "rizhao", "dezhou", "weihai", "dongying", "heze", "jining", "weifang", "zaozhuang", "liaocheng"] },
    { "name": "henan", "cities": ["zhengzhou", "luoyang", "kaifeng", "pingdingshan", "puyang", "anyang", "xuchang", "nanyang", "xinyang", "zhoukou", "xinxiang", "jiaozuo", "sanmenxia", "shangqiu"] },
    { "name": "hubei", "cities": ["wuhan", "xiangfan", "xiaogan", "shiyan", "jingzhou", "huangshi", "yichang", "huanggang", "enshi", "ezhou", "jianghan", "suizao", "jingsha", "xianning"] },
    { "name": "hunan", "cities": ["changsha", "xiangtan", "yueyang", "zhuzhou", "huaihua", "yongzhou", "yiyang", "zhangjiajie", "changde", "hengyang", "xiangxi", "shaoyang", "loudi", "chenzhou"] },
    { "name": "guangdong", "cities": ["guangzhou", "shenzhen", "dongwan", "foshan", "zhuhai", "shantou", "shaoguan", "jiangmen", "meizhou", "jieyang", "zhongshan", "heyuan", "huizhou", "maoming", "zhanjiang", "yangjiang", "chaozhou", "yunfu", "shanwei", "chaoyang", "zhaoqing", "shunde", "qingyuan"] },
    { "name": "guangxi", "cities": ["nanning", "guilin", "liuzhou", "wuzhou", "laibin", "guigang", "yulin", "hezhou"] },
    { "name": "hainan", "cities": ["haikou", "sanya"] },
    { "name": "zhongqing", "cities": ["yuzhong", "dadukou", "jiangbei", "shapingba", "jiulongpo", "nanan", "beibei", "wansheng", "shuangqiao", "yubei", "banan", "wanzhou", "fuling", "qianjiang", "changshou"] },
    { "name": "sichuan", "cities": ["chengdou", "dazhou", "nanchong", "leshan", "mianyang", "deyang", "najiang", "suining", "yibin", "bazhong", "zigong", "kangding", "panzhihua"] },
    { "name": "guizhou", "cities": ["guiyang", "zunyi", "anshun", "qianxinan", "douyun"] },
    { "name": "yunnan", "cities": ["kunming", "lijiang", "zhaotong", "yuxi", "lincang", "wenshan", "honghe", "chuxiong", "dali"] },
    { "name": "xicang", "cities": ["lasa", "linzhi", "rikaze", "changdou"] },
    { "name": "shanxi", "cities": ["xian", "xianyang", "yanan", "hanzhong", "yulin", "shangnan", "lueyang", "yijun", "linyou", "baihe"] },
    { "name": "gansu", "cities": ["lanzhou", "jinchang", "tianshui", "wuwei", "zhangye", "pingliang", "jiuquan"] },
    { "name": "qinghai", "cities": ["huangnan", "hainan", "xining", "haidong", "haixi", "haibei", "guoluo", "yushu"] },
    { "name": "ningxia", "cities": ["yinchuan", "wuzhong"] },
    { "name": "xinjiang", "cities": ["wulumuqi", "hami", "kashi", "bayinguoleng", "changji", "yili", "aletai", "kelamayi", "boertala"] },
    { "name": "xianggang", "cities": ["zhongxiqu", "wanziqu", "dongqu", "nanqu", "jiulong-youjianwangqu", "jiulong-shenshuibuqu", "jiulong-jiulongchengqu", "jiulong-huangdaxianqu", "jiulong-guantangqu", "xinjie-beiqu", "xinjie-dapuqu", "xinjie-shatianqu", "xinjie-xigongqu", "xinjie-quanwanqu", "xinjie-tunmenqu", "xinjie-yuanlangqu", "xinjie-kuiqingqu", "xinjie-lidaoqu"] },
    { "name": "aomen", "cities": ["huadimatangqu", "shenganduonitangqu", "datangqu", "wangdetangqu", "fengshuntangqu", "jiamotangqu", "shengfangjigetangqu", "ludangcheng"] }
  ]';

    private $city2 = '[{ "name": "北京", "cities": ["西城", "东城", "崇文", "宣武", "朝阳", "海淀", "丰台", "石景山", "门头沟", "房山", "通州", "顺义", "大兴", "昌平", "平谷", "怀柔", "密云", "延庆"] },
    { "name": "天津", "cities": ["青羊", "河东", "河西", "南开", "河北", "红桥", "塘沽", "汉沽", "大港", "东丽", "西青", "北辰", "津南", "武清", "宝坻", "静海", "宁河", "蓟县", "开发区"] },
    { "name": "河北", "cities": ["石家庄", "秦皇岛", "廊坊", "保定", "邯郸", "唐山", "邢台", "衡水", "张家口", "承德", "沧州", "衡水"] },
    { "name": "山西", "cities": ["太原", "大同", "长治", "晋中", "阳泉", "朔州", "运城", "临汾"] },
    { "name": "内蒙古", "cities": ["呼和浩特", "赤峰", "通辽", "锡林郭勒", "兴安"] },
    { "name": "辽宁", "cities": ["大连", "沈阳", "鞍山", "抚顺", "营口", "锦州", "丹东", "朝阳", "辽阳", "阜新", "铁岭", "盘锦", "本溪", "葫芦岛"] },
    { "name": "吉林", "cities": ["长春", "吉林", "四平", "辽源", "通化", "延吉", "白城", "辽源", "松原", "临江", "珲春"] },
    { "name": "黑龙江", "cities": ["哈尔滨", "齐齐哈尔", "大庆", "牡丹江", "鹤岗", "佳木斯", "绥化"] },
    { "name": "上海", "cities": ["浦东", "杨浦", "徐汇", "静安", "卢湾", "黄浦", "普陀", "闸北", "虹口", "长宁", "宝山", "闵行", "嘉定", "金山", "松江", "青浦", "崇明", "奉贤", "南汇"] },
    { "name": "江苏", "cities": ["南京", "苏州", "无锡", "常州", "扬州", "徐州", "南通", "镇江", "泰州", "淮安", "连云港", "宿迁", "盐城", "淮阴", "沐阳", "张家港"] },
    { "name": "浙江", "cities": ["杭州", "金华", "宁波", "温州", "嘉兴", "绍兴", "丽水", "湖州", "台州", "舟山", "衢州"] },
    { "name": "安徽", "cities": ["合肥", "马鞍山", "蚌埠", "黄山", "芜湖", "淮南", "铜陵", "阜阳", "宣城", "安庆"] },
    { "name": "福建", "cities": ["福州", "厦门", "泉州", "漳州", "南平", "龙岩", "莆田", "三明", "宁德"] },
    { "name": "江西", "cities": ["南昌", "景德镇", "上饶", "萍乡", "九江", "吉安", "宜春", "鹰潭", "新余", "赣州"] },
    { "name": "山东", "cities": ["青岛", "济南", "淄博", "烟台", "泰安", "临沂", "日照", "德州", "威海", "东营", "荷泽", "济宁", "潍坊", "枣庄", "聊城"] },
    { "name": "河南", "cities": ["郑州", "洛阳", "开封", "平顶山", "濮阳", "安阳", "许昌", "南阳", "信阳", "周口", "新乡", "焦作", "三门峡", "商丘"] },
    { "name": "湖北", "cities": ["武汉", "襄樊", "孝感", "十堰", "荆州", "黄石", "宜昌", "黄冈", "恩施", "鄂州", "江汉", "随枣", "荆沙", "咸宁"] },
    { "name": "湖南", "cities": ["长沙", "湘潭", "岳阳", "株洲", "怀化", "永州", "益阳", "张家界", "常德", "衡阳", "湘西", "邵阳", "娄底", "郴州"] },
    { "name": "广东", "cities": ["广州", "深圳", "东莞", "佛山", "珠海", "汕头", "韶关", "江门", "梅州", "揭阳", "中山", "河源", "惠州", "茂名", "湛江", "阳江", "潮州", "云浮", "汕尾", "潮阳", "肇庆", "顺德", "清远"] },
    { "name": "广西", "cities": ["南宁", "桂林", "柳州", "梧州", "来宾", "贵港", "玉林", "贺州"] },
    { "name": "海南", "cities": ["海口", "三亚"] },
    { "name": "重庆", "cities": ["渝中", "大渡口", "江北", "沙坪坝", "九龙坡", "南岸", "北碚", "万盛", "双桥", "渝北", "巴南", "万州", "涪陵", "黔江", "长寿"] },
    { "name": "四川", "cities": ["成都", "达州", "南充", "乐山", "绵阳", "德阳", "内江", "遂宁", "宜宾", "巴中", "自贡", "康定", "攀枝花"] },
    { "name": "贵州", "cities": ["贵阳", "遵义", "安顺", "黔西南", "都匀"] },
    { "name": "云南", "cities": ["昆明", "丽江", "昭通", "玉溪", "临沧", "文山", "红河", "楚雄", "大理"] },
    { "name": "西藏", "cities": ["拉萨", "林芝", "日喀则", "昌都"] },
    { "name": "陕西", "cities": ["西安", "咸阳", "延安", "汉中", "榆林", "商南", "略阳", "宜君", "麟游", "白河"] },
    { "name": "甘肃", "cities": ["兰州", "金昌", "天水", "武威", "张掖", "平凉", "酒泉"] },
    { "name": "青海", "cities": ["黄南", "海南", "西宁", "海东", "海西", "海北", "果洛", "玉树"] },
    { "name": "宁夏", "cities": ["银川", "吴忠"] },
    { "name": "新疆", "cities": ["乌鲁木齐", "哈密", "喀什", "巴音郭楞", "昌吉", "伊犁", "阿勒泰", "克拉玛依", "博尔塔拉"] },
    { "name": "香港", "cities": ["中西区", "湾仔区", "东区", "南区", "九龙-油尖旺区", "九龙-深水埗区", "九龙-九龙城区", "九龙-黄大仙区", "九龙-观塘区", "新界-北区", "新界-大埔区", "新界-沙田区", "新界-西贡区", "新界-荃湾区", "新界-屯门区", "新界-元朗区", "新界-葵青区", "新界-离岛区"] },
    { "name": "澳门", "cities": ["花地玛堂区", "圣安多尼堂区", "大堂区", "望德堂区", "风顺堂区", "嘉模堂区", "圣方济各堂区", "路氹城"] }]';


    private $citys = [
        "Beijing"=> "北京",
        "Tianjin"=> "天津",
        "Shanghai"=> "上海",
        "Chongqing"=> "重庆",
        "Yinchuan"=> "银川",
        "Shizuishan"=> "石嘴山",
        "Wuzhong"=> "吴忠",
        "Guyuan"=> "固原",
        "Zhongwei"=> "中卫",
        "Wulumuqi"=> "乌鲁木齐",
        "Kelamayi"=> "克拉玛依",
        "Lasa"=> "拉萨",
        "Huhehaote"=> "呼和浩特",
        "Baotou"=> "包头",
        "Wuhai"=> "乌海",
        "Chifeng"=> "赤峰",
        "Tongliao"=> "通辽",
        "Eerduosi"=> "鄂尔多斯",
        "Hulunbeier"=> "呼伦贝尔",
        "Bayannaoer"=> "巴彦淖尔",
        "Wulanchabu"=> "乌兰察布",
        "Nanning"=> "南宁",
        "Liuzhou"=> "柳州",
        "Guilin"=> "桂林",
        "Wuzhou"=> "梧州",
        "Beihai"=> "北海",
        "Chongzuo"=> "崇左",
        "Laibin"=> "来宾",
        "Hezhou"=> "贺州",
        "Yulin"=> "玉林",
        "Baise"=> "百色",
        "Hechi"=> "河池",
        "Qinzhou"=> "钦州",
        "Fangchenggang"=> "防城港",
        "Guigang"=> "贵港",
        "Haerbin"=> "哈尔滨",
        "Daqing"=> "大庆",
        "Qiqihaer"=> "齐齐哈尔",
        "Jiamusi"=> "佳木斯",
        "Jixi"=> "鸡西",
        "Hegang"=> "鹤岗",
        "Shuangyashan"=> "双鸭山",
        "Mudanjiang"=> "牡丹江",
        "Yichun"=> "伊春",
        "Qitaihe"=> "七台河",
        "Heihe"=> "黑河",
        "Suihua"=> "绥化",
        "Changchun"=> "长春",
        "Jilin"=> "吉林",
        "Siping"=> "四平",
        "Liaoyuan"=> "辽源",
        "Tonghua"=> "通化",
        "Baishan"=> "白山",
        "Songyuan"=> "松原",
        "Baicheng"=> "白城",
        "Shenyang"=> "沈阳",
        "Dalian"=> "大连",
        "Anshan"=> "鞍山",
        "Fushun"=> "抚顺",
        "Benxi"=> "本溪",
        "Dandong"=> "丹东",
        "Jinzhou"=> "锦州",
        "Yingkou"=> "营口",
        "Fuxin"=> "阜新",
        "Liaoyang"=> "辽阳",
        "Panjin"=> "盘锦",
        "Tieling"=> "铁岭",
        "Chaoyang"=> "朝阳",
        "Huludao"=> "葫芦岛",
        "Shijiazhuang"=> "石家庄",
        "Tangshan"=> "唐山",
        "Handan"=> "邯郸",
        "Qinghuangdao"=> "秦皇岛",
        "Baoding"=> "保定",
        "Zhangjiakou"=> "张家口",
        "Chengde"=> "承德",
        "Langfang"=> "廊坊",
        "Cangzhou"=> "沧州",
        "Hengshui"=> "衡水",
        "Xingtai"=> "邢台",
        "Jinan"=> "济南",
        "Qingdao"=> "青岛",
        "Zibo"=> "淄博",
        "Zaozhuang"=> "枣庄",
        "Dongying"=> "东营",
        "Yantai"=> "烟台",
        "Weifang"=> "潍坊",
        "Jining"=> "济宁",
        "Taian"=> "泰安",
        "Weihai"=> "威海",
        "Rizhao"=> "日照",
        "Laiwu"=> "莱芜",
        "Linyi"=> "临沂",
        "Dezhou"=> "德州",
        "Liaocheng"=> "聊城",
        "Heze"=> "菏泽",
        "Binzhou"=> "滨州",
        "Nanjing"=> "南京",
        "Zhenjiang"=> "镇江",
        "Changzhou"=> "常州",
        "Wuxi"=> "无锡",
        "Suzhou"=> "苏州",
        "Xuzhou"=> "徐州",
        "Lianyungang"=> "连云港",
        "Huaian"=> "淮安",
        "Yancheng"=> "盐城",
        "Yangzhou"=> "扬州",
        "Taizhou"=> "泰州",
        "Nantong"=> "南通",
        "Suqian"=> "宿迁",
        "Hefei"=> "合肥",
        "Bengbu"=> "蚌埠",
        "Wuhu"=> "芜湖",
        "Huainan"=> "淮南",
        "Bozhou"=> "亳州",
        "Fuyang"=> "阜阳",
        "Huaibei"=> "淮北",
        "Suzhou"=> "宿州",
        "Chuzhou"=> "滁州",
        "Anqing"=> "安庆",
        "Chaohu"=> "巢湖",
        "Maanshan"=> "马鞍山",
        "Xuancheng"=> "宣城",
        "Huangshan"=> "黄山",
        "Chizhou"=> "池州",
        "Tongling"=> "铜陵",
        "Hangzhou"=> "杭州",
        "Jiaxing"=> "嘉兴",
        "Huzhou"=> "湖州",
        "Ningbo"=> "宁波",
        "Jinhua"=> "金华",
        "Wenzhou"=> "温州",
        "Lishui"=> "丽水",
        "Shaoxing"=> "绍兴",
        "Quzhou"=> "衢州",
        "Zhoushan"=> "舟山",
        "Taizhou"=> "台州",
        "Fuzhou"=> "福州",
        "Xiamen"=> "厦门",
        "Quanzhou"=> "泉州",
        "Sanming"=> "三明",
        "Nanping"=> "南平",
        "Zhangzhou"=> "漳州",
        "Putian"=> "莆田",
        "Ningde"=> "宁德",
        "Longyan"=> "龙岩",
        "Guangzhou"=> "广州",
        "Shenzhen"=> "深圳",
        "Shantou"=> "汕头",
        "Huizhou"=> "惠州",
        "Zhuhai"=> "珠海",
        "Jieyang"=> "揭阳",
        "Foshan"=> "佛山",
        "Heyuan"=> "河源",
        "Yangjiang"=> "阳江",
        "Maoming"=> "茂名",
        "Zhanjiang"=> "湛江",
        "Meizhou"=> "梅州",
        "Zhaoqing"=> "肇庆",
        "Shaoguan"=> "韶关",
        "Chaozhou"=> "潮州",
        "Dongguan"=> "东莞",
        "Zhongshan"=> "中山",
        "Qingyuan"=> "清远",
        "Jiangmen"=> "江门",
        "Shanwei"=> "汕尾",
        "Yunfu"=> "云浮",
        "Haikou"=> "海口",
        "Sanya"=> "三亚",
        "Kunming"=> "昆明",
        "Qujing"=> "曲靖",
        "Yuxi"=> "玉溪",
        "Baoshan"=> "保山",
        "Zhaotong"=> "昭通",
        "Lijiang"=> "丽江",
        "Puer"=> "普洱",
        "Lincang"=> "临沧",
        "Guiyang"=> "贵阳",
        "Liupanshui"=> "六盘水",
        "Zunyi"=> "遵义",
        "Anshun"=> "安顺",
        "Chengdu"=> "成都",
        "Mianyang"=> "绵阳",
        "Deyang"=> "德阳",
        "Guangyuan"=> "广元",
        "Zigong"=> "自贡",
        "Panzhihua"=> "攀枝花",
        "Leshan"=> "乐山",
        "Nanchong"=> "南充",
        "Neijiang"=> "内江",
        "Suining"=> "遂宁",
        "Guangan"=> "广安",
        "Luzhou"=> "泸州",
        "Dazhou"=> "达州",
        "Meishan"=> "眉山",
        "Yibin"=> "宜宾",
        "Yaan"=> "雅安",
        "Ziyang"=> "资阳",
        "Changsha"=> "长沙",
        "Zhuzhou"=> "株洲",
        "Xiangtan"=> "湘潭",
        "Hengyang"=> "衡阳",
        "Yueyang"=> "岳阳",
        "Chenzhou"=> "郴州",
        "Yongzhou"=> "永州",
        "Shaoyang"=> "邵阳",
        "Huaihua"=> "怀化",
        "Changde"=> "常德",
        "Yiyang"=> "益阳",
        "Zhangjiajie"=> "张家界",
        "Loudi"=> "娄底",
        "Wuhan"=> "武汉",
        "Xiangfan"=> "襄樊",
        "Yichang"=> "宜昌",
        "Huangshi"=> "黄石",
        "Ezhou"=> "鄂州",
        "Suizhou"=> "随州",
        "Jingzhou"=> "荆州",
        "Jingmen"=> "荆门",
        "Shiyan"=> "十堰",
        "Xiaogan"=> "孝感",
        "Huanggang"=> "黄冈",
        "Xianning"=> "咸宁",
        "Zhengzhou"=> "郑州",
        "Luoyang"=> "洛阳",
        "Kaifeng"=> "开封",
        "Luohe"=> "漯河",
        "Anyang"=> "安阳",
        "Xinxiang"=> "新乡",
        "Zhoukou"=> "周口",
        "Sanmenxia"=> "三门峡",
        "Jiaozuo"=> "焦作",
        "Pingdingshan"=> "平顶山",
        "Xinyang"=> "信阳",
        "Nanyang"=> "南阳",
        "Hebi"=> "鹤壁",
        "Puyang"=> "濮阳",
        "Xuchang"=> "许昌",
        "Shangqiu"=> "商丘",
        "Zhumadian"=> "驻马店",
        "Taiyuan"=> "太原",
        "DaTong"=> "大同",
        "Xinzhou"=> "忻州",
        "Yangquan"=> "阳泉",
        "Changzhi"=> "长治",
        "Jincheng"=> "晋城",
        "Shuozhou"=> "朔州",
        "Jinzhong"=> "晋中",
        "Yuncheng"=> "运城",
        "Linfen"=> "临汾",
        "Lvliang"=> "吕梁",
        "Xian"=> "西安",
        "Xianyang"=> "咸阳",
        "Tongchuan"=> "铜川",
        "Yanan"=> "延安",
        "Baoji"=> "宝鸡",
        "Weinan"=> "渭南",
        "Hanzhoung"=> "汉中",
        "Ankang"=> "安康",
        "Shangluo"=> "商洛",
        "Yulin"=> "榆林",
        "Lanzhou"=> "兰州",
        "Tianshui"=> "天水",
        "Pingliang"=> "平凉",
        "Jiuquan"=> "酒泉",
        "Jiayuguan"=> "嘉峪关",
        "Jinchang"=> "金昌",
        "baiyiin"=> "白银",
        "Wuwei"=> "武威",
        "Zhangye"=> "张掖",
        "Qingyang"=> "庆阳",
        "Dingxi"=> "定西",
        "Longnan"=> "陇南",
        "Xining"=> "西宁",
        "Nanchang"=> "南昌",
        "Jiujiang"=> "九江",
        "Ganzhou"=> "赣州",
        "Jian"=> "吉安",
        "Yingtan"=> "鹰潭",
        "Shangrao"=> "上饶",
        "Pingxiang"=> "萍乡",
        "Jingdezhen"=> "景德镇",
        "Xinyu"=> "新余",
        "Yichun"=> "宜春",
        "hebei"=>"河北省",
        "Shaanxi"=>"山西省",
        "namenggu"=>"内蒙古",
        "liaoning"=>"辽宁省",
        "jilin"=>"吉林省",
        "heilongjiang"=>"黑龙江省",
        "jiangsu"=>"江苏省",
        "zhejiang"=>"浙江省",
        "anhui"=>"安徽省",
        "fujian"=>"福建省",
        "jiangxi"=>"江西省",
        "shandong"=>"山东省",
        "henan"=>"河南省",
        "hubei"=>"湖北省",
        "hunan"=>"湖南省",
        "guangdong"=>"广东省",
        "guangxi"=>"广西省",
        "hainan"=>"海南省",
        "sichuan"=>"四川省",
        "guizhou"=>"贵州省",
        "yunnan"=>"云南省",
        "xicang"=>"西藏自治区",
        "shanxi"=>"陕西省",
        "gansu"=>"甘肃省",
        "qinghai"=>"青海省",
        "ningxia"=>"宁夏回族自治区",
        "xinjiang"=>"新疆维吾尔自治区",
        "xianggang"=>"香港",
        "aomen"=>"澳门"
    ];

    public function get_citys(){
        $citys = $this->citys;
        $new = [];
        foreach ($citys as $k=>$v){
            $new[strtolower($k)] = $v;
        }
        return $new;
    }

    public function get_province($pinying){
        $city1 = json_decode($this->city1,true);
        $city2 = json_decode($this->city2,true);
        foreach ($city1 as $k=>$v){
            if(strtolower($v['name'])==strtolower($pinying)){
                return $city2[$k]['name'];
            }
        }
    }

    public function get_city($province,$city){
        $city1 = json_decode($this->city1,true);
        $city2 = json_decode($this->city2,true);
        $new = [];
        $k1 = $k2 = 0;
        foreach ($city1 as $k=>$v){
            if(strtolower($v['name'])==strtolower($province)){
                $new = $city1[$k];
                $k1 = $k;
            }
        }
        foreach ($new["cities"]  as $kk=>$vv){
            if(strtolower($vv)==strtolower($city)){
                $k2 = $kk;
            }
        }
        return $city2[$k1]['cities'][$k2];
    }


    public function get_city_pinyin($province,$cityname){
        $city1 = json_decode($this->city1,true);
        $city2 = json_decode($this->city2,true);
        $new = [];
        $k1 = $k2 = 0;
        foreach ($city2 as $k=>$v){
            if(strpos($province,$v['name'])!==false){
                $new = $city2[$k];
                $k1 = $k;
            }
        }
        if(isset($new['cities'])) {
            foreach ($new["cities"] as $kk => $vv) {
                if (strpos($cityname, $vv) !== false) {
                    $k2 = $kk;
                }
            }
        }
        return $city1[$k1]['cities'][$k2];
    }

}